// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTLG1I3iaOuII2mVp9zQkRpph3uiiLSo',
    appId: '1:102244948117:web:79535ed2e96744139d239c',
    messagingSenderId: '102244948117',
    projectId: 'countus-40b7e',
    authDomain: 'countus-40b7e.firebaseapp.com',
    storageBucket: 'countus-40b7e.appspot.com',
    measurementId: 'G-37DNDNTFPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALUbX_6tlDPLBaRlSCmKi6P9BF6ta2aYE',
    appId: '1:102244948117:android:d79d399378ef1a1d9d239c',
    messagingSenderId: '102244948117',
    projectId: 'countus-40b7e',
    storageBucket: 'countus-40b7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOHHPIL8dznO-3BXFrxykzKo-Yyx6RPxU',
    appId: '1:102244948117:ios:b9e17e30059df6669d239c',
    messagingSenderId: '102244948117',
    projectId: 'countus-40b7e',
    storageBucket: 'countus-40b7e.appspot.com',
    iosBundleId: 'com.example.satu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOHHPIL8dznO-3BXFrxykzKo-Yyx6RPxU',
    appId: '1:102244948117:ios:b9e17e30059df6669d239c',
    messagingSenderId: '102244948117',
    projectId: 'countus-40b7e',
    storageBucket: 'countus-40b7e.appspot.com',
    iosBundleId: 'com.example.satu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaTLG1I3iaOuII2mVp9zQkRpph3uiiLSo',
    appId: '1:102244948117:web:f84f2d24dbba75bf9d239c',
    messagingSenderId: '102244948117',
    projectId: 'countus-40b7e',
    authDomain: 'countus-40b7e.firebaseapp.com',
    storageBucket: 'countus-40b7e.appspot.com',
    measurementId: 'G-YVWMB6FCSL',
  );

}